name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master # Adjust if your default branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Assuming your Express.js application doesn't require Python.
    # Removed the Setup Python step as it's not necessary for Node.js environments.

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install AWS Elastic Beanstalk CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        . ~/.nvm/nvm.sh
        nvm install node
        npm install -g awsebcli

    - name: Initialize Elastic Beanstalk Application
      run: eb init -p "Node.js" tylerolmstedco --region us-east-2

    - name: Deploy to Elastic Beanstalk
      run: eb deploy Tylerolmstedco-env
