name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master # Set to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Set to your Python version

    - name: Upgrade pip and setuptools
      run: |
          python -m pip install --upgrade pip setuptools

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
        pip install -r requirements.txt

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2' # Set to your AWS region
      run: |
        eb deploy Tylerolmstedeb-env --profile default

