name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master # Adjust if your default branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your Node.js version here

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install AWS Elastic Beanstalk CLI
      run: |
        pip install awsebcli

    - name: Install NPM dependencies
      run: |
        npm install

    - name: Initialize Elastic Beanstalk Application
      run: |
        eb init -p "Node.js" tylerolmstedco --region us-east-2

    - name: Deploy to Elastic Beanstalk
      run: |
        eb deploy Tylerolmstedco-env
